* Time Out: GamerSegmentation

Exhumed with the [[https://web.archive.org/web/20090211145348/http://web.mac.com:80/rsdancey/RSDanceyBlog/Blog/Entries/2007/8/15_Time_Out:__Gamer_Segmentation.html][Wayback Machine]].
 

** RSDancey On The Web

2007 August 15

I noticed that Sean Reynolds’ web site appears to be off-line.  He hosted this article for a long time and I used to point people to his site to read it, but since it’s not available, I’ve reprinted it here.

I have a high confidence in this data. I think it does the best job of explaining ‘who is who’ in the gaming community, and there are a lot of lessons about how to structure successful RPG experiences embedded in it.

Sean says: In 1999, WotC had a market research group do an extensive survey of RPG gamers in an attempt to better understand the RPG market. The questions were of the "rate this topic from 1, not at all, to 5, very strongly." The results of some of the questions were used to classify the respondents into categories in order to better understand what sort of experiences (and thus, products) these gamers were looking for. WotC released this information publicly, although it was not widely circulated outside of RPG game publishers. Ryan has given me permission to repost his summary of these results, which he originally posted on one of the forums of Steve Jackson Games' Pyramid Magazine.

The original results were shared with WotC R&D before being released to the public. It's interesting information, and the graph did really work out as described below, with most of the dots clustered into the middle of each quadrant and a smaller cluster in the middle of the graph. Just be aware that these results are tendencies; someone whose answers landed them in the "Thinkers" quadrant can still enjoy aspects of the other four quadrants. It's a market research study, not a psionic blueprint of the gaming populations.

Imagine two axis.

The horizontal axis is Strategic Focused to Tactical Focused.

"Strategic" means "a perspective larger than the immediate future and surroundings". "Tactical" means "a perspective limited to the immediate future and the immediate surroundings."

"Invade the Normandy beaches on D-Day" is Strategic. "Take out that bunker before the machine gun kills us all!" is Tactical.

The vertical axis is Combat Focused to Story Focused.

"Combat Focused" means "Conflict resolution is interesting to me." "Story Focused" means "The world and the interaction of the characters is interesting to me."

"Kick this door down and kill anything that moves" is Combat focused. "This door has the Mark of Malvena; the space within should be safe for
us to rest in" is Story focused.

This creates four quadrants. Starting in the upper left and moving clockwise, label these quadrants Thinkers, Power Gamers, Character
Actors, and Storytellers

- A Thinker is a player who most enjoys the game when it delivers Strategic/Combat Focus. This kind of person is likely to enjoy min-maxing a character, spending hours out of game to find every conceivable advantage available in the system to deliver maximum damage from behind maximum protection, even if the min-maxing produces results that are seemingly illogical/impossible. This kind of person wants to solve puzzles and can keep track of long chains of facts and clues.


    * A Power Gamer is a player who most enjoys the game when it delivers a Tactical/Combat Focus. This kind of person is likely to enjoy playing a character that has a minimum of personality (often, this kind of person plays a character that is simply an extension of the player). This kind of player enjoys short, intense gaming experiences. The consequences of a failed action are minimized for this player, who will roll up a new character and return to the fray without much thought for the storyline implications of that action.


    * A Character Actor is a player who most enjoys the game when it delivers a Tactical/Story Focus. This kind of person is likely to enjoy the act of theater; using voice, posture, props, etc. to express a character's actions and dialog. This player will have a character that makes sub-optimal choices (from an external perspective) to ensure that the character's actions are "correct" from the perspective of the character's motivations, ethics, and knowledge.


    * A Storyteller is a player who most enjoys the game when it delivers a Strategic/Story Focus. This kind of person finds enjoyment from the logical progression of the narrative of the scenario. There should be a beginning, a middle and an end. Characters should develop over time in reaction to their experiences. This player will look for a  non-rules answer to inconsistencies or anachronisms in the game experience.


    * There is a fifth type of player, who does not express a preference along any of the four axis. This person is a "basic roleplayer", who finds enjoyment from strategy, tactics, combat and story in rough equilibrium.


Roughly, each of the four quadrants accounts for approximately 22% of the player community. About 12% fall into the fifth, centric position.


We generated this data by asking a series of questions during the Market Research study in 1999 to create what is called a "segmentation" of the players. The questions were not designed to find these four quadrants; they correlate to all kinds of player interest and behavior. The original survey had several hundred questions, but only about two dozen have a bearing on the segmentation results. Once the study was complete, the data was plotted in several dimensions to look for clusters of responses; those clusters became the five player types. Once we knew the segmentation was there, we reverse-engineered the axis, by comparing the responses of the people in each segment to find similarities.


What we don't know (and won't for several years) is if people's play preferences change over time. What we do know is that the age distribution across the five segments was undifferentiated (meaning there were people of all ages in each group), and the number of years a person had been playing RPGs had no effect either (meaning that people don't seem to migrate to a segment based on their depth of experience). We also found no additional segmentation based on what games people identified as their "favorite"; in other words, there are just as many Power Gamers as there are Storytellers who like Vampire, and just as many Thinkers as Character Actors who like D&D.


All of the people who indicated a strong interest in RPGs identified eight "core values" that they look for in the RPG experience. These 8 core values are more important than the segments; that is, if these 8 things aren't present in the play experience it won't matter if the game generally supports a given segment's interests - the players will find the experience dissatisfying. These 8 core values are:


    * Strong Characters and Exciting Story

    * Role Playing

    * Complexity Increases over Time

    * Requires Strategic Thinking

    * Competitive

    * Add on sets/New versions available

    * Uses imagination

    * Mentally challenging


In other words, even the players who enjoy a "Tactical Focus" still want to be challenged to use Strategic Thinking; likewise, even the Combat Focus player wants a Strong Character and Exciting Story. A person who segments into a "Tactical Focus" segment, when compared to the population as a whole is likely to be perceived as someone who enjoys Strategy; only when compared to the population of people who enjoy RPGs is the difference visible between the hard-core strategic players and the slightly less hard-core tactical players.


Similarly, people who play RPGs don't want to just play DOOM. The most hard-core fan of melee combat still wants to fight opponents that are meaningful and wants his or her character to act in a way proscribed by the archetypes of the genre or property being simulated.


I have used the analogy of fans of "the color blue" to discuss this effect. To the general population, blue is just blue. But to a true fan, there are many shades of blue, each with its own unique properties. RPG gamers have more in common with each other than they do with non-RPG gamers, but within their own community, there are noticeable differences that can be categorized.


We think that there is data to support the idea that people who enjoy being GM/DMs tend to cluster into the Storyteller segment. Interestingly, based on our own internal profiling of the staff, there's some data to support the idea that good game designers tend to cluster into the "Thinker" segment. In other words, good DMs don't make the best game designers, and vice versa. As with all things though, there will be exceptions and special cases.


We also have data that suggests that most groups are made up of people who segment differently (that is, monolithic segmentation within a gaming group is rare), and in fact, having different kinds of players tends to make the RPG experience work better over the long haul.


Eventually, we would like to bring some of this technology to the gaming table, to allow GM/DMs to profile their players and then customize a scenario to ensure that each player is getting support for the style of play they most enjoy, and that if a segment is missing from the table, content can be removed or changed to avoid having the adventure "bog down" when nobody has the interest/intellectual tools to cope with a problem targeting an unrepresented segment.


Unlike some of the discussions which rage from time to time about the nature of game design paradigms, the above information was extracted from general market research data that had as much bias as possible removed. It reflects deep seated psychological aspects of the gamer mind and tells us some very interesting things about how we can make our products more interesting to our target consumers.

Here’s a quick revisitation of some data that’s germane to this ongoing discussion...

Wednesday, August 15, 2007

Time Out:  Gamer Segmentation

Comments Widget
 
Made on a Mac
